spring:
  application:
    name: gaoyang-spring-ai
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:7b
        temperature: 0.7
        num-predict: 1024
      embedding:
        model: nomic-embed-text
      init:
        timeout: 1m
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
    vectorstore:
      pgvector:
        initialize-schema: always
        dimensions: 768
        index-type: HNSW
        distance-type: COSINE_DISTANCE

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

searxng:
  base-url: http://localhost:8888

logging:
  level:
    # SimpleLoggerAdvisorDEBUG
    org.springframework.ai.chat.client.advisor: DEBUG
    # OpenAI/HTTP
    org.springframework.ai.openai: DEBUG
    org.springframework.ai.ollama: DEBUG