spring:
  application:
    name: gaoyang-spring-ai
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:7b
        temperature: 0.7
        num-predict: 1024
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: gy5211314
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
